export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'
export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGOUT_REQUEST = 'USER_LOGOUT_REQUEST'
export const USER_LOGOUT = 'USER_LOGOUT'

export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST'
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS'
export const USER_DETAILS_FAIL = 'USER_DETAILS_FAIL'

export const GET_POST_REQUEST = 'GET_POST_REQUEST'
export const POSTS_SUCCESS = 'POSTS_SUCCESS'
export const POST_SUCCESS = 'POST_SUCCESS'
export const POST_FAIL = 'POST_FAIL'
export const ADD_POST_REQUEST = 'ADD_POST_REQUEST'
export const ADD_POST = 'ADD_POST'

export const DELETE_POST_REQUEST = 'DELETE_POST_REQUEST'
export const POST_DELETE = 'POST_DELETE'

export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST'
export const USER_UPDATE_REQUEST_SUCCESS = 'USER_UPDATE_REQUEST_SUCCESS'
export const USER_UPDATE_REQUEST_FAIL = 'USER_UPDATE_REQUEST_FAIL'

export const GET_SINGLE_POST = 'GET_SINGLE_POST'
export const GET_SINGLE_POST_SUCCESS = 'GET_SINGLE_POST_SUCCESS'

export const POST_UPDATE_REQUEST = 'POST_UPDATE_REQUEST'
export const POST_UPDATE_REQUEST_SUCCESS = 'POST_UPDATE_REQUEST_SUCCESS'
export const POST_UPDATE_REQUEST_FAIL = 'POST_UPDATE_REQUEST_FAIL'
